"""empty message

Revision ID: 141145edf43a
Revises: 
Create Date: 2020-05-25 21:06:15.195330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '141145edf43a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factorization',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('factors', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('number')
    )
    op.create_table('prime',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('prime', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('number')
    )
    op.create_index(op.f('ix_prime_prime'), 'prime', ['prime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prime_prime'), table_name='prime')
    op.drop_table('prime')
    op.drop_table('factorization')
    # ### end Alembic commands ###
